name: First Work Flow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            First-input:
                description: Hello World
                type: string
                required: true
                default: "Default"
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check and download npm
              run: |
                echo $(npm -v)
                sudo apt install npm
                echo $GITHUB_REF
                echo "String: ${{inputs.First-input}}"
    Check-out:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: check on variables
              run: echo $GITHUB_REF
            

                